name: Conda pytest
on: push

jobs:
  push_to_registry:
    name: Build docker file for testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install the conda
        shell: bash -l {0}
        run: |
          conda create -n test python=3.10 -y
          conda init
          conda activate test
          conda install -c conda-forge xesmf esmpy -y
          export ESMFMKFILE='/usr/share/miniconda/lib/esmf.mk'

      - name: Install the repo
        shell: bash -l {0}
        run: |
          conda activate test
          pip install -e .

      - name: run pytest
        shell: bash -l {0}
        run: |
          conda activate test
          which python
          python -m pytest
