name: Python package tests

on:
  push:
  schedule:
    - cron: "0 12 * * 1"
jobs:
  call-run-docker-tests:
    uses: openclimatefix/.github/.github/workflows/docker-test.yml@v1.8.1
    with:
      docker_file: "Dockerfile"

